postgres:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "Zstvgcs@9102"
  dbname: "deepface_v5"
  showSQL: true
  showtime: true
  connMaxLifetime: 1000
  maxOpenConns: 10
  maxIdleConns: 1000
  # 需要删除的数据库表(默认即可，不需要改)
  tables: ["faces","faces_index","nonmotor_capture","nonmotor_capture_index","pedestrian_capture","pedestrian_capture_index","vehicle_capture","vehicle_capture_index"]
#  tables: ["faces"]
deletetime:
  # 删除开始时间，一般不需要修改
  startTime: "2006-01-02 15:04:05"
  # 删除结束时间
  endTime: "2020-03-11 11:30:00"
garbage:
  maxChannel: 1000
  URL: "127.0.0.1:9333"
  # seaweedfs回收阈值，越小回收的越快
  garbageThreshold: 0.2
  # 是否删除数据库记录 false 不删除  true 删除
  deleteDB: true
log:
  # false为info级别 true为debug级别
  debug: true